project:
  type: website
  output-dir: docs

website:
  title: "personal-christara-laing"
  site-url: "https://hostrosts69.github.io/personal-christara-laing/"
  favicon: "/images/hello.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: articles/article_01.qmd
        text: Reversing Arrays
      - href: articles/article_02.qmd
        text: My Additons
      - href: articles/GC_calender/index.qmd
        text: GC Calender
      - text: Articles
        menu:
          - text: Reversing Arrays in JS
            href:  articles/article_01.qmd
          - text: Checkerboard in JS
            href:  articles/article_03.qmd
          - text: My Additons
            href: articles/article_02.qmd
    

format:
  html:
    theme: 
      light: united
      dark: darkly
    css: styles.css
    toc: true
