project:
  type: website
  output-dir: docs

website:
  title: "personal-christara-laing"
  site-url: "https://hostrosts69.github.io/personal-christara-laing/"
  favicon: "/images/hello.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: articles/article_01.qmd
        text: Reversing An Array
      - href: 404.qmd
        text: Writing Your Own Loop
      - href: articles/GC_calender/index.qmd
        text: GC Calender
      - href: posts/index.qmd
        text: Blog
    

format:
  html:
    theme: 
      light: united
      dark: darkly
    css: styles.css
    toc: true






