project:
  type: website
  output-dir: docs

website:
  title: "warmup-christara-laing"
  site-url: "https://hostrosts69.github.io/warmup-christara-laing/"
  favicon: "/images/hello.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: articles/article_01.qmd
        text: Reversing An Array
      - href: 404.qmd
        text: Writing Your Own Loop
    

format:
  html:
    theme: 
      light: united
      dark: darkly
    css: styles.css
    toc: true






