project:
  type: website
  output-dir: docs

website:
  title: "warmup-christara-laing"
  image: Untitled.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true






