project:
  type: website
  output-dir: docs

website:
  title: "warmup-christara-laing"
  favicon: images/hello.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: articles/article_01.qmd
        text: Reversing An Array
    

format:
  html:
    theme: 
      light: united
      dark: darkly
    css: styles.css
    
    toc: true






